public with sharing class Constants {
    public static final String COMMIT_ATTACHMENT_NAME = 'Flosum-Git_CommitAttachmentWithHistorysIds';
    public static final String EDIT_ATTACHMENT_NAME = 'Flosum-Git_EditAttachmentWithComponents';
    public static final String SINGLE_OPERATION_EDIT_ATTACHMENT_NAME = 'Flosum-Git_Single_EditAttachmentWithComponents';
    public static final String DELETE_ATTACHMENT_NAME = 'Flosum-Git_ComponentsForDelete';
    public static final String SINGLE_OPERATION_DELETE_ATTACHMENT_NAME = 'Flosum-Git_Single_ComponentsForDelete';
    public static final String SYNC_ATTACHMENT_FOR_BRANCH_NAME = 'SyncAttachmentBranch';
    public static final String SYNC_ATTACHMENT_FOR_REPOSITORY_NAME = 'SyncAttachmentRepository';

    public static final String MISSING_CONNECTION_DETAILS_SETTING_ERROR = 'Cant find connection details record';
    public static final String WRONG_PROVIDER_VALUE_ERROR_MESSAGE = 'Wrong Git provider value';
    public static final String MISSING_CONNECTION_ERROR = 'Cant find connection record';

    public static final String WRONG_LOG_TYPE_ERROR = 'Wrong Log type.';
    public static final String COMMIT_LOG = 'Commit';
    public static final String SYNC_LOG = 'Synchronization';
    public static final String SYSTEM_LOG = 'System';
}